version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export PATH=./node_modules/.bin:$PATH
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run test

  post_build:
    commands:
      - |
        if [[ "$CODEBUILD_INITIATOR" =~ ^codepipeline* ]]; then
          export CREDS=$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)
          export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .Token)
          export AWS_DEFAULT_REGION=us-east-2
          export AWS_ACCOUNT_NUMBER=$(aws sts get-caller-identity --query Account --output text)
          cdk bootstrap aws://$AWS_ACCOUNT_NUMBER/us-east-2
          npm run build:template
          npm run cdk:publish:assets
        else 
          echo "Not running in CodePipeline, skipping CDK template generation and assets publishing"
        fi

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - echo START -- Build and Publish Docker image for createGeneratedDocument.handler
      - docker build -t create-generated-document-lambda-execution-environment:latest ./build/handlers/createGeneratedDocument -f ./build/handlers/createGeneratedDocument/createGeneratedDocument.handler.Dockerfile
      - docker tag create-generated-document-lambda-execution-environment:latest $AWS_ACCOUNT_NUMER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/create-generated-document-lambda-execution-environment:latest
      - docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/create-generated-document-lambda-execution-environment:latest
      - echo END -- Publish Docker image for createGeneratedDocument.handler
reports:
  arn:aws:codebuild:us-east-2:546515125053:report-group/codebuild-processproof-document-templating-service:
    files:
      - "junit.xml"
    base-directory: "build"
    discard-paths: no

artifacts:
  files:
    - build/**/*
    - template.yml
