version: 0.2
env:
  variables:
    TEMPLATE_FILENAME: template.yml
    TEMPLATE_PACKAGED_FILENAME: template.packaged.yml
    S3_BUCKET: arn:aws:s3:::cdk-hnb659fds-assets-546515125053-us-east-2
    S3_PREFIX: process-proof-codepipeline-builds

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export PATH=./node_modules/.bin:$PATH
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run test
  post_build:
    commands:
      - env
      - npm run build:template
      - aws cloudformation package --template-file $TEMPLATE_FILENAME --s3-bucket $S3_BUCKET --s3-prefix $S3_PREFIX --output-template-file $TEMPLATE_PACKAGED_FILENAME
      - echo Build completed on `date`

reports:
  arn:aws:codebuild:us-east-2:546515125053:report-group/codebuild-processproof-document-templating-service:
    files:
      - "junit.xml"
    base-directory: "build"
    discard-paths: no

artifacts:
  files:
    - build/**/*
    - $TEMPLATE_FILENAME
