version: 0.2
env:
  variables:
    TEMPLATE_FILENAME: template.yml
    TEMPLATE_PACKAGED_FILENAME: template.packaged.yml
    S3_BUCKET: arn:aws:s3:::processproof-document-templating-service-codebuild-artifacts

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export PATH=./node_modules/.bin:$PATH
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run test
  post_build:
    commands:
      - npm run build:template
      - |
        if [[ "$CODEBUILD_WEBHOOK_TRIGGER" =~ ^pr/* ]]; then
          echo "Skipping deployment for PR builds"
          exit 0
        else
          export CREDS=$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)
          export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .Token)
          echo "[default]" > ~/.aws/config
          echo "region = us-east-2" >> ~/.aws/config
          echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/config
          echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/config
          cdk bootstrap aws://546515125053/us-east-2
          cdk synth > $TEMPLATE_FILENAME
          cdk-assets -p cdk.out/*assets.json publish --verbose
        fi

      - echo Build completed on `date`
reports:
  arn:aws:codebuild:us-east-2:546515125053:report-group/codebuild-processproof-document-templating-service:
    files:
      - "junit.xml"
    base-directory: "build"
    discard-paths: no

artifacts:
  files:
    - build/**/*
    - $TEMPLATE_FILENAME
