version: 0.2
env:
  variables:
    TEMPLATE_FILENAME: template.yml
    TEMPLATE_PACKAGED_FILENAME: template.packaged.yml
    S3_BUCKET: arn:aws:s3:::processproof-document-templating-service-codebuild-artifacts

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export PATH=./node_modules/.bin:$PATH
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:sd
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run test

  post_build:
    commands:
      - env
      - npm run build:template
      - |
        if [[ "$CODEBUILD_INITIATOR" =~ ^codepipeline* ]]; then
          export CREDS=$(curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)
          export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r .AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r .SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r .Token)
          
          export AWS_CONFIG_FILE=$(pwd)/.aws-config
          export AWS_SHARED_CREDENTIALS_FILE=$(pwd)/.aws-credentials
          export AWS_SDK_LOAD_CONFIG=1
          export AWS_DEFAULT_REGION=us-east-2
          
          echo "[default]" > $(pwd)/.aws-credentials
          echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> $(pwd)/.aws-credentials
          echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> $(pwd)/.aws-credentials
          echo "region = us-east-2" > $(pwd)/.aws-credentials
          echo "output = json" >> $(pwd)/.aws-credentials
          cat ./.aws-credentials
          
          echo "[default]" > $(pwd)/.aws-config
          echo "region = us-east-2" > $(pwd)/.aws-config
          echo "output = json" >> $(pwd)/.aws-config
          cat ./.aws-config
        
          cdk-assets -p cdk.out/*assets.json publish --verbose
        else 
          echo "Not running in CodePipeline, skipping CDK assets publishing"
        fi

      - echo Build completed on `date`
reports:
  arn:aws:codebuild:us-east-2:546515125053:report-group/codebuild-processproof-document-templating-service:
    files:
      - "junit.xml"
    base-directory: "build"
    discard-paths: no

artifacts:
  files:
    - build/**/*
    - $TEMPLATE_FILENAME
