configuration:
  ParameterOverrides: |
    '{
        "AwsEnv": "DEV",
        "S3PrimaryRegion": "us-east-1",
        "DocumentTemplatesBucketArn": "DocumentTemplatesBucketArn here",
        "DocumentTemplatesS3KeyPrefix": "DocumentTemplatesS3KeyPrefix-here",
        "DocumentTemplatesDynamodbTableArn": "DocumentTemplatesDynamodbTableArn-here",
        "DocumentTemplatesDynamodbPartitionKeyPrefix": "DocumentTemplatesDynamodbPartitionKeyPrefix-here",
        "GeneratedDocumentsBucketArn": "GeneratedDocumentsBucketArn-here",
        "GeneratedDocumentsS3KeyPrefix": "GeneratedDocumentsS3KeyPrefix-here",
        "GeneratedDocumentsDynamodbTableArn": "GeneratedDocumentsDynamodbTableArn-here",
        "GeneratedDocumentsDynamodbPartitionKeyPrefix": "GeneratedDocumentsDynamodbPartitionKeyPrefix-here"
    }'
