Parameters:
  AWSENV:
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - TEST
      - STAGING
      - PROD
    Description: The AWS environment deployed to
  GotenbergServiceInstanceEnableSsh:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Whether to enable SSH access to the Gotenberg service instance
  SsmParameterValueuseast2processproofgotenbergamiC96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /us-east-2/processproof-gotenberg-ami
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
  GotenbergServiceSecurityGroup7A6A64AC:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DocumentTemplatingService/GotenbergServiceSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: vpc-058c5ee1e09681197
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceSecurityGroup/Resource
  GotenbergServiceSecurityGroupHttpIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: 0.0.0.0/0
      FromPort: 3000
      GroupId:
        Fn::GetAtt:
          - GotenbergServiceSecurityGroup7A6A64AC
          - GroupId
      IpProtocol: tcp
      ToPort: 3000
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceSecurityGroupHttpIngress
  GotenbergServiceSecurityGroupSshIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: 0.0.0.0/0
      FromPort: 22
      GroupId:
        Fn::GetAtt:
          - GotenbergServiceSecurityGroup7A6A64AC
          - GroupId
      IpProtocol: tcp
      ToPort: 22
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceSecurityGroupSshIngress
    Condition: GotenbergServiceInstanceEnableSshCondition
  GotenbergServiceInstanceInstanceRoleF036C99D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      Tags:
        - Key: Name
          Value: DocumentTemplatingService/GotenbergServiceInstance
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstance/InstanceRole/Resource
  GotenbergServiceInstanceInstanceProfile2AB77017:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: GotenbergServiceInstanceInstanceRoleF036C99D
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstance/InstanceProfile
  GotenbergServiceInstanceA66C5FDBb0f955a9fcb6487c:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      IamInstanceProfile:
        Ref: GotenbergServiceInstanceInstanceProfile2AB77017
      ImageId:
        Ref: SsmParameterValueuseast2processproofgotenbergamiC96584B6F00A464EAD1953AFF4B05118Parameter
      InstanceType: c6gd.medium
      KeyName: TempKeypair
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: "0"
          GroupSet:
            - Fn::GetAtt:
                - GotenbergServiceSecurityGroup7A6A64AC
                - GroupId
          SubnetId: subnet-036f5f2f9c607cf2a
      Tags:
        - Key: Name
          Value: DocumentTemplatingService/GotenbergServiceInstance
      UserData:
        Fn::Base64: |-
          #!/bin/bash
          service docker start
          usermod -a -G docker ec2-user
          chkconfig docker on
          docker container run --name gotenbergInstance -p 3000:3000 gotenberg/gotenberg:7.9
    DependsOn:
      - GotenbergServiceInstanceInstanceRoleF036C99D
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstance/Resource
  GotenbergServiceInstanceBaseUrlA0BD3E86:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub:
          - /${AWS_ENV}/document-templating-service/gotenberg-base-url
          - AWS_ENV:
              Ref: AWSENV
      Type: String
      Value:
        Fn::Sub:
          - http://${GOTENBERG_IP}:3000
          - GOTENBERG_IP:
              Fn::GetAtt:
                - GotenbergServiceInstanceA66C5FDBb0f955a9fcb6487c
                - PrivateIp
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstanceBaseUrl/Resource
  LambdaExecutionRoleD5C26073:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: Lambda Execution Role
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: DocumentTemplatingService/LambdaExecutionRole/Resource
  mergeDocumentAndData2658F40D:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-546515125053-us-east-2
        S3Key: cb69319e3de270be44b4313631f69bbc9add6a40be742d7f294de93a67a69e7f.zip
      Environment:
        Variables:
          AWS_ENV:
            Ref: AWSENV
          GOTENBERG_BASE_URL:
            Fn::GetAtt:
              - GotenbergServiceInstanceBaseUrlA0BD3E86
              - Value
          PROCESSPROOF_GENERAL_PRIVATE_BUCKET_ARN:
            Fn::Sub:
              - "{{resolve:ssm:/${AWS_ENV}/processproof-s3-buckets/general-private-bucket-arn}}"
              - AWS_ENV:
                  Ref: AWSENV
          PROCESSPROOF_PUBLIC_DOCUMENTS_BUCKET_ARN:
            Fn::Sub:
              - "{{resolve:ssm:/${AWS_ENV}/processproof-s3-buckets/public-documents-bucket-arn}}"
              - AWS_ENV:
                  Ref: AWSENV
      Handler: mergeDocumentAndData.handler
      Role:
        Fn::GetAtt:
          - LambdaExecutionRoleD5C26073
          - Arn
      Runtime: nodejs18.x
    DependsOn:
      - LambdaExecutionRoleD5C26073
    Metadata:
      aws:cdk:path: DocumentTemplatingService/mergeDocumentAndData/Resource
      aws:asset:path: asset.cb69319e3de270be44b4313631f69bbc9add6a40be742d7f294de93a67a69e7f
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/32QwU7DMAyGn4V7atgYEhzZJNBuU3mAyUu9ymvjoDgZQlXfHbdQwYnT79hffv/yGp42cHeDH1r5pqt6PsHwltF3bneWAyYMlCm5mjSW5MkZeBzIr40iXxLnz9cUy/tE/9/YS5tI1e1FM4o5GbDUo2MMMNSxn9uLLuNDimfujVINU7rE0v5G+5tzdD2GU4MwvBTxmaNM46U2g/sjqlJWeJ7E3rAtvqO8RTV/Y3dRGp4/zoSdorVtc6qfE4xOYkNw0dvr6hFWD3a9izJXqUjmQFB/6xcdjYHBWQEAAA==
    Metadata:
      aws:cdk:path: DocumentTemplatingService/CDKMetadata/Default
Conditions:
  GotenbergServiceInstanceEnableSshCondition:
    Fn::Equals:
      - "true"
      - Ref: GotenbergServiceInstanceEnableSsh
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

