Parameters:
  AWSENV:
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - TEST
      - STAGING
      - PROD
    Description: The AWS environment deployed to
  GotenbergServiceInstanceEnableSsh:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Whether to enable SSH access to the Gotenberg service instance
  SsmParameterValueuseast2processproofgotenbergamiC96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /us-east-2/processproof-gotenberg-ami
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
  GotenbergServiceSecurityGroup7A6A64AC:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DocumentTemplatingService/GotenbergServiceSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: vpc-058c5ee1e09681197
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceSecurityGroup/Resource
  GotenbergServiceSecurityGroupHttpIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: 0.0.0.0/0
      FromPort: 3000
      GroupId:
        Fn::GetAtt:
          - GotenbergServiceSecurityGroup7A6A64AC
          - GroupId
      IpProtocol: tcp
      ToPort: 3000
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceSecurityGroupHttpIngress
  GotenbergServiceSecurityGroupSshIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: 0.0.0.0/0
      FromPort: 22
      GroupId:
        Fn::GetAtt:
          - GotenbergServiceSecurityGroup7A6A64AC
          - GroupId
      IpProtocol: tcp
      ToPort: 22
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceSecurityGroupSshIngress
    Condition: GotenbergServiceInstanceEnableSshCondition
  GotenbergServiceInstanceInstanceRoleF036C99D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      Tags:
        - Key: Name
          Value: DocumentTemplatingService/GotenbergServiceInstance
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstance/InstanceRole/Resource
  GotenbergServiceInstanceInstanceProfile2AB77017:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: GotenbergServiceInstanceInstanceRoleF036C99D
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstance/InstanceProfile
  GotenbergServiceInstanceA66C5FDB8eab42f3697fe4d9:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      IamInstanceProfile:
        Ref: GotenbergServiceInstanceInstanceProfile2AB77017
      ImageId:
        Ref: SsmParameterValueuseast2processproofgotenbergamiC96584B6F00A464EAD1953AFF4B05118Parameter
      InstanceType: c6gd.medium
      KeyName: TempKeypair
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: "0"
          GroupSet:
            - Fn::GetAtt:
                - GotenbergServiceSecurityGroup7A6A64AC
                - GroupId
          SubnetId: subnet-036f5f2f9c607cf2a
      Tags:
        - Key: Name
          Value: DocumentTemplatingService/GotenbergServiceInstance
      UserData:
        Fn::Base64: |-
          #!/bin/bash
          service docker start
          usermod -a -G docker ec2-user
          chkconfig docker on
          docker container run --name gotenbergInstance -p 3000:3000 gotenberg/gotenberg:7.9
          docker start gotenbergInstance
    DependsOn:
      - GotenbergServiceInstanceInstanceRoleF036C99D
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstance/Resource
  GotenbergServiceInstanceBaseUrlA0BD3E86:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub:
          - /${AWS_ENV}/document-templating-service/gotenberg-base-url
          - AWS_ENV:
              Ref: AWSENV
      Type: String
      Value:
        Fn::Sub:
          - http://${GOTENBERG_IP}:3000
          - GOTENBERG_IP:
              Fn::GetAtt:
                - GotenbergServiceInstanceA66C5FDB8eab42f3697fe4d9
                - PrivateIp
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstanceBaseUrl/Resource
  LambdaExecutionRoleD5C26073:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: Lambda Execution Role
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::546515125053:policy/LambdaPrivateSubnetExecutionRolePolicy
    Metadata:
      aws:cdk:path: DocumentTemplatingService/LambdaExecutionRole/Resource
  generatedDocumentSecurityGroupCA8A4E03:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Automatic security group for Lambda Function DocumentTemplatingServicegeneratedDocumentA9E2753B
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: vpc-058c5ee1e09681197
    Metadata:
      aws:cdk:path: DocumentTemplatingService/generatedDocument/SecurityGroup/Resource
  generatedDocumentFE6B32DC:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-546515125053-us-east-2
        S3Key: 64fcc8fa80ddb42adbfb3e6dba0a913341af50ac9c4b24f52494fe7174b6f9a6.zip
      Environment:
        Variables:
          AWS_ENV:
            Ref: AWSENV
          GOTENBERG_BASE_URL:
            Fn::GetAtt:
              - GotenbergServiceInstanceBaseUrlA0BD3E86
              - Value
          PROCESSPROOF_GENERAL_PRIVATE_BUCKET_ARN:
            Fn::Sub:
              - "{{resolve:ssm:/${AWS_ENV}/processproof-s3-buckets/general-private-bucket-arn}}"
              - AWS_ENV:
                  Ref: AWSENV
          PROCESSPROOF_PUBLIC_DOCUMENTS_BUCKET_ARN:
            Fn::Sub:
              - "{{resolve:ssm:/${AWS_ENV}/processproof-s3-buckets/public-documents-bucket-arn}}"
              - AWS_ENV:
                  Ref: AWSENV
          S3_VPC_ENDPOINT_USEAST2: vpce-0e24695c3398ce129
      Handler: generateDocument.handler
      Role:
        Fn::GetAtt:
          - LambdaExecutionRoleD5C26073
          - Arn
      Runtime: nodejs18.x
      VpcConfig:
        SecurityGroupIds:
          - Fn::GetAtt:
              - generatedDocumentSecurityGroupCA8A4E03
              - GroupId
        SubnetIds:
          - subnet-036f5f2f9c607cf2a
          - subnet-064e80ed435060622
    DependsOn:
      - LambdaExecutionRoleD5C26073
    Metadata:
      aws:cdk:path: DocumentTemplatingService/generatedDocument/Resource
      aws:asset:path: asset.64fcc8fa80ddb42adbfb3e6dba0a913341af50ac9c4b24f52494fe7174b6f9a6
      aws:asset:is-bundled: false
      aws:asset:property: Code
  ApiF70053CD:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name:
        Fn::Sub:
          - processproof-{AWS_ENV}-document-templating-service
          - AWS_ENV:
              Ref: AWSENV
      ProtocolType: HTTP
    Metadata:
      aws:cdk:path: DocumentTemplatingService/Api/Resource
  ApiDefaultStage189A7074:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: ApiF70053CD
      AutoDeploy: true
      StageName: $default
    Metadata:
      aws:cdk:path: DocumentTemplatingService/Api/DefaultStage/Resource
  ApiGETgenerateDocumentgenerateDocumentLambdaHttpIntegrationEBA67B53:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: ApiF70053CD
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - generatedDocumentFE6B32DC
          - Arn
      PayloadFormatVersion: "2.0"
    Metadata:
      aws:cdk:path: DocumentTemplatingService/Api/GET--generateDocument/generateDocumentLambdaHttpIntegration/Resource
  ApiGETgenerateDocumentgenerateDocumentLambdaHttpIntegrationPermission6E056E4E:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - generatedDocumentFE6B32DC
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-east-2:546515125053:"
            - Ref: ApiF70053CD
            - /*/*/generateDocument
    Metadata:
      aws:cdk:path: DocumentTemplatingService/Api/GET--generateDocument/generateDocumentLambdaHttpIntegration-Permission
  ApiGETgenerateDocument155C2E1E:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: ApiF70053CD
      AuthorizationType: NONE
      RouteKey: GET /generateDocument
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: ApiGETgenerateDocumentgenerateDocumentLambdaHttpIntegrationEBA67B53
    Metadata:
      aws:cdk:path: DocumentTemplatingService/Api/GET--generateDocument/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/31Qy27CMBD8Fu6OeVRV21sBqS03lH4AWpwlNSR25N2AUJR/79okak49zXg9npn1Sr+96G4xgxtlprhklT3q7pvBXNT25PYQoEbGoHIk3waDSoSHDs1KVGjaYPn+GXzbRPX/g50rAxKpnSMGJ04iGHmvLNS6y32VxiOO1/vgT7YSFVEd2wXryr9q0569qqA+FqC7j9YZtt7F6ynfY6gtkZzE7ukARMik1xHkrDetuSBvgGTTxpbAeIP7VbaVp+vGpq0YyqEeYxlgdM59y9j3kW69K2yaJ+P4Qion0fCPvVpkUDU/oBez9+Hz5xGnqYOi+2JuYnjER3pkKS+xSRHJd75Afab5dfmql8/ifyZrs9A6tjXq/IG/QOxWh/gBAAA=
    Metadata:
      aws:cdk:path: DocumentTemplatingService/CDKMetadata/Default
Conditions:
  GotenbergServiceInstanceEnableSshCondition:
    Fn::Equals:
      - "true"
      - Ref: GotenbergServiceInstanceEnableSsh
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

