Parameters:
  AWSENV:
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - TEST
      - STAGING
      - PROD
    Description: The AWS environment deployed to
  GotenbergServiceInstanceEnableSsh:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: Whether to enable SSH access to the Gotenberg service instance
  SsmParameterValueawsserviceamiamazonlinuxlatestal2023amikernel61arm64C96584B6F00A464EAD1953AFF4B05118Parameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Resources:
  PrivateSubnetUsEast2ASubnet374C74EF:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2a
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: DocumentTemplatingService/PrivateSubnetUsEast2A
      VpcId: vpc-55c2b13c
    Metadata:
      aws:cdk:path: DocumentTemplatingService/PrivateSubnetUsEast2A/Subnet
  PrivateSubnetUsEast2ARouteTable24F3AAF9:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: DocumentTemplatingService/PrivateSubnetUsEast2A
      VpcId: vpc-55c2b13c
    Metadata:
      aws:cdk:path: DocumentTemplatingService/PrivateSubnetUsEast2A/RouteTable
  PrivateSubnetUsEast2ARouteTableAssociation2034DD60:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateSubnetUsEast2ARouteTable24F3AAF9
      SubnetId:
        Ref: PrivateSubnetUsEast2ASubnet374C74EF
    Metadata:
      aws:cdk:path: DocumentTemplatingService/PrivateSubnetUsEast2A/RouteTableAssociation
  GotenbergServiceSecurityGroup7A6A64AC:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DocumentTemplatingService/GotenbergServiceSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: vpc-55c2b13c
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceSecurityGroup/Resource
  GotenbergServiceSecurityGroupHttpIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: 0.0.0.0/0
      FromPort: 3000
      GroupId:
        Fn::GetAtt:
          - GotenbergServiceSecurityGroup7A6A64AC
          - GroupId
      IpProtocol: tcp
      ToPort: 3000
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceSecurityGroupHttpIngress
  GotenbergServiceSecurityGroupSshIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: 0.0.0.0/0
      FromPort: 22
      GroupId:
        Fn::GetAtt:
          - GotenbergServiceSecurityGroup7A6A64AC
          - GroupId
      IpProtocol: tcp
      ToPort: 22
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceSecurityGroupSshIngress
    Condition: GotenbergServiceInstanceEnableSshCondition
  GotenbergServiceInstanceInstanceRoleF036C99D:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      Tags:
        - Key: Name
          Value: DocumentTemplatingService/GotenbergServiceInstance
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstance/InstanceRole/Resource
  GotenbergServiceInstanceInstanceProfile2AB77017:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: GotenbergServiceInstanceInstanceRoleF036C99D
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstance/InstanceProfile
  GotenbergServiceInstanceA66C5FDB582147246eb5ebdb:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      IamInstanceProfile:
        Ref: GotenbergServiceInstanceInstanceProfile2AB77017
      ImageId:
        Ref: SsmParameterValueawsserviceamiamazonlinuxlatestal2023amikernel61arm64C96584B6F00A464EAD1953AFF4B05118Parameter
      InstanceType: c6gd.medium
      KeyName: TempKeypair
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: "0"
          GroupSet:
            - Fn::GetAtt:
                - GotenbergServiceSecurityGroup7A6A64AC
                - GroupId
          PrivateIpAddress: 10.0.0.1
          SubnetId:
            Ref: PrivateSubnetUsEast2ASubnet374C74EF
      Tags:
        - Key: Name
          Value: DocumentTemplatingService/GotenbergServiceInstance
      UserData:
        Fn::Base64: |-
          #!/bin/bash
          yum update -y
          yum -y install docker
          service docker start
          usermod -a -G docker ec2-user
          chkconfig docker on
          docker container run --name gotenbergInstance -p 3000:3000 public.ecr.aws/citizensadvice/gotenberg:latest
    DependsOn:
      - GotenbergServiceInstanceInstanceRoleF036C99D
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstance/Resource
  GotenbergServiceInstanceBaseUrlA0BD3E86:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub:
          - /${AWS_ENV}/document-templating-service/gotenberg-base-url
          - AWS_ENV:
              Ref: AWSENV
      Type: String
      Value:
        Fn::Sub:
          - http://${GOTENBERG_IP}:3000
          - GOTENBERG_IP:
              Fn::GetAtt:
                - GotenbergServiceInstanceA66C5FDB582147246eb5ebdb
                - PrivateIp
    Metadata:
      aws:cdk:path: DocumentTemplatingService/GotenbergServiceInstanceBaseUrl/Resource
  LambdaExecutionRoleD5C26073:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      Description: Lambda Execution Role
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: DocumentTemplatingService/LambdaExecutionRole/Resource
  mergeDocumentAndData2658F40D:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-546515125053-us-east-2
        S3Key: a35a6dc2567bd55b9c2973be011ac635201fea92e16c67ec59fa396e13395188.zip
      Environment:
        Variables:
          AWS_ENV:
            Ref: AWSENV
          GOTENBERG_BASE_URL:
            Fn::GetAtt:
              - GotenbergServiceInstanceBaseUrlA0BD3E86
              - Value
          PROCESSPROOF_GENERAL_PRIVATE_BUCKET_ARN:
            Fn::Sub:
              - "{{resolve:ssm:/${AWS_ENV}/processproof-s3-buckets/general-private-bucket-arn}}"
              - AWS_ENV:
                  Ref: AWSENV
          PROCESSPROOF_PUBLIC_DOCUMENTS_BUCKET_ARN:
            Fn::Sub:
              - "{{resolve:ssm:/${AWS_ENV}/processproof-s3-buckets/public-documents-bucket-arn}}"
              - AWS_ENV:
                  Ref: AWSENV
      Handler: mergeDocumentAndData.handler
      Role:
        Fn::GetAtt:
          - LambdaExecutionRoleD5C26073
          - Arn
      Runtime: nodejs18.x
    DependsOn:
      - LambdaExecutionRoleD5C26073
    Metadata:
      aws:cdk:path: DocumentTemplatingService/mergeDocumentAndData/Resource
      aws:asset:path: asset.a35a6dc2567bd55b9c2973be011ac635201fea92e16c67ec59fa396e13395188
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/31RwU7DMAz9Fu5pYAMkOG6TQLtVLffJTb3Ka+OgOBlCVf+dNKMqJ07PsV+e/eytfn3SD3fwJYVp+2KgRo91ANOrw5lL8GAxoFcVioveoErE04hmq8fS0xUC1rFhDDN7jSoXA35AM+CaX3M7EWcIAjlWNZroKXy/exc/M/nfxJE7jyLqyBKATZZf4kkRWD1W7tZ1waVcenemIbFE7GzRE3erv79mJzWAbVrQ41tkk8dM5SVOAo8nEMEgejdDeut9ND2GPUjST9yD45byx8xI++xStzzV7x4nxa5FfZH76+ZFb57TCS5CVPjIgSzq6oY/EHPVY54BAAA=
    Metadata:
      aws:cdk:path: DocumentTemplatingService/CDKMetadata/Default
Conditions:
  GotenbergServiceInstanceEnableSshCondition:
    Fn::Equals:
      - "true"
      - Ref: GotenbergServiceInstanceEnableSsh
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

